# Generated by Django 2.0.3 on 2018-04-18 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payrollapp', '0002_auto_20180404_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('human_resources_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='usermetadata',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='paidtimeoffrequests',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], max_length=1),
        ),
    ]
