# Generated by Django 2.0.3 on 2018-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0004_auto_20180417_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='title',
            field=models.CharField(default='Cash money', max_length=64),
            preserve_default=False,
        ),
    ]
