# Generated by Django 2.0.3 on 2018-04-18 07:16

from django.db import migrations, models
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0005_expenses_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='file',
            field=models.ImageField(null=True, upload_to=payrollapp.models.expense_directory_path),
        ),
    ]
