# Generated by Django 2.0.2 on 2018-04-24 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payrollapp', '0007_auto_20180424_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaycheckInformation',
            fields=[
                ('paycheck_id', models.AutoField(primary_key=True, serialize=False)),
                ('payday', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('witholdings', models.DecimalField(decimal_places=2, max_digits=16)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wages',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='paidtimeoffrequests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Wages',
        ),
    ]
