# Generated by Django 2.0.3 on 2018-04-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payrollapp', '0009_auto_20180424_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationHours',
            fields=[
                ('vacation_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_vacation_hours', models.IntegerField(default=72)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='user_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('No current affiliation', 'No current affiliation')], default='Active', max_length=25),
        ),
    ]
