# Generated by Django 2.0.3 on 2018-04-25 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payrollapp', '0010_auto_20180424_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidTimeOffHours',
            fields=[
                ('vacation_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_hours', models.IntegerField(default=160)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacationhours',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='VacationHours',
        ),
    ]
