# Generated by Django 2.0.3 on 2018-05-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0011_auto_20180424_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='company',
            field=models.CharField(default='No company', max_length=255, unique=True),
        ),
    ]
