# Generated by Django 2.0.3 on 2018-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0012_usermetadata_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
