# Generated by Django 2.0.3 on 2018-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0013_timesheetsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='group',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Human Resources', 'Human Resources')], default='Employee', max_length=32),
        ),
    ]
