# Generated by Django 2.0.3 on 2018-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0014_usermetadata_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='company',
            field=models.CharField(default='No company', max_length=255),
        ),
    ]
