# Generated by Django 2.0.2 on 2018-05-09 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payrollapp', '0017_expenses_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetApprovals',
            fields=[
                ('time_sheet_approvals_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetEntry',
            fields=[
                ('time_sheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_hours', models.IntegerField()),
                ('time_sheet_approvals_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.TimeSheetApprovals')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='timesheetsubmission',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='TimeSheetSubmission',
        ),
    ]
