# Generated by Django 2.0.3 on 2018-05-09 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payrollapp', '0019_timesheetapprovals_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidTimeOffApproval',
            fields=[
                ('paid_time_off_approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaidTimeOffEntry',
            fields=[
                ('paid_time_off_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('paid_time_off_approval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.PaidTimeOffApproval')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='paidtimeoff',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='paidtimeoffrequests',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PaidTimeOff',
        ),
        migrations.DeleteModel(
            name='PaidTimeOffRequests',
        ),
    ]
