# Generated by Django 2.0.2 on 2018-05-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0020_auto_20180509_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetapprovals',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
